[project]
name = "banking-account-api"
version = "1.0.0"
description = "Standalone Banking Account API with FastAPI"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.0.0"
]
